FROM node:6
MAINTAINER Jack Hu <hello@jackhu.top>

# Pre-install npm packages
RUN npm install -g node-gyp && \
    npm install -g pm2 && \
    npm cache clean && \
    rm -rf /tmp/* /var/tmp/*

RUN mkdir -p /var/www
WORKDIR /var/www
COPY . /var/www
RUN npm install --production
EXPOSE 3000
CMD [ "npm", "start" ]
